name: GitHub Actions Demo
on:
  push:
    branches:
      - develop
jobs:
  linter:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install poetry
        uses: actions/install-poetry
      - name: Install dependencies
        run: poetry install --ansi
      - name: Linter run
        run: flake8 ./src main.py